name: Test Dev

on:
  push:
    branches: [dev]
  pull_request:
    branches: [dev]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    name: Tests

    steps:
      - uses: actions/checkout@v6
      - name: Go Setup
        uses: ./.github/actions/go-setup

      - name: Run Tests
        uses: ./.github/actions/test

      - name: Build release binaries
        uses: ./.github/actions/build
