name: Test

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    name: Run Tests

    steps:
      - uses: actions/checkout@v6
      - name: Go Setup
        uses: ./.github/actions/go-setup

      - name: Run Tests
        uses: ./.github/actions/test

      - name: Send coverage
        uses: ./.github/actions/coverage
